SistemaWeb_UnidadPracticas/Controllers/SIGUPController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using CapaEntidad;
using CapaNegocio;
using Newtonsoft.Json;
//using QuestPDF.Fluent;//Para exportar a pdf
//using QuestPDF.Helpers;

namespace SistemaWeb_UnidadPracticas.Controllers
{
    [Authorize]
    public class SIGUPController : Controller
    {
        // GET: SIGUP
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CategoriaHerramienta()
        {
            return View();
        }

        public ActionResult Herramientas()
        {
            return View();
        }

        public ActionResult Usuarios()
        {
            return View();
        }

        public ActionResult Estadisticas()
        {
            return View();
        }

        public ActionResult Administradores()
        {
            return View();
        } 

        public ActionResult Prestamos()
        {
            return View();
        }
        public ActionResult HistorialPrestamos()
        {
            return View();
        }


        /*--------------CATEGORIA---------------------*/
        #region CATEGORIA
        [HttpGet] /*Una URL que devuelve datos, un httpost se le pasan los valores y despues devuelve los datos  */
        public JsonResult ListarCategoria() /*D este json se puede controlar que mas ver, igualar elementos, etc*/
        {
            List<EN_CategoriaHerramienta> oLista = new List<EN_CategoriaHerramienta>();
            oLista = new RN_CategoriaHerramienta().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
            /*El json da los datos, jala los datos de esa lista, en data*/
        }

        [HttpGet]
        public JsonResult ListarCategoriaEnHerramienta()
        {
            List<EN_CategoriaHerramienta> oLista = new List<EN_CategoriaHerramienta>();
            oLista = new RN_CategoriaHerramienta().ListarCategoriaEnHerramienta();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarCategoria(EN_CategoriaHerramienta objeto) /*De este json se puede controlar que mas ver, igualar elementos, etc*/
        {
            object resultado;/*Va a permitir almacenar cualquier tipo de resultado (en este caso int o booelan, dependiendi si es creacion o edicion)*/
            string mensaje = string.Empty;

            if (objeto.idCategoria == 0)/*Es decir, si el id es 0 en inicio (el valor es 0 inicialmente) significa que es
             una categoria nueva, por lo que se ha dado dando clic con el boton de crear*/
            {
                resultado = new RN_CategoriaHerramienta().Registrar(objeto, out mensaje);/*El metodo registrar
                 de tipo int, devuelve el id registrado*/
            }
            else
            {/*Pero si el id es diferente de 0, es decir ya existe, entonces se esta editando
                 a una categoria, por lo que indica que se ha dado clic en el boton de editar, eso lo comprobamos
                 con los alert comentados*/
                resultado = new RN_CategoriaHerramienta().Editar(objeto, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }


        [HttpPost]
        public JsonResult EliminarCategoria(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new RN_CategoriaHerramienta().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

       
        #endregion

        /*--------------MARCA HERRAMIENTA---------------------*/
        #region MARCA HERRAMIENTA
        [HttpGet] /*Una URL que devuelve datos, un httpost se le pasan los valores y despues devuelve los datos  */
        public JsonResult ListarMarca() /*D este json se puede controlar que mas ver, igualar elementos, etc*/
        {
            List<EN_MarcaHerramienta> oLista = new List<EN_MarcaHerramienta>();
            oLista = new RN_MarcaHerramienta().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
            /*El json da los datos, jala los datos de esa lista, en data*/
        }

        [HttpGet]
        public JsonResult ListarMarcaEnHerramienta() /*D este json se puede controlar que mas ver, igualar elementos, etc*/
        {
            List<EN_MarcaHerramienta> oLista = new List<EN_MarcaHerramienta>();
            oLista = new RN_MarcaHerramienta().ListarMarcaEnHerramienta();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
            /*El json da los datos, jala los datos de esa lista, en data*/
        }

        [HttpPost]
        public JsonResult guardarMarca(EN_MarcaHerramienta marca)
        {
            object resultado = null;
            string mensaje = string.Empty;

            if (marca.idMarca == 0)
            {
                resultado = new RN_MarcaHerramienta().registrar(marca, out mensaje);
            }
            else
            {
                resultado = new RN_MarcaHerramienta().editarMarca(marca, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult eliminarMarca(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;
            respuesta =  new RN_MarcaHerramienta().eliminarMarca(id, out mensaje);
            if (respuesta)
            {
                return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { resultado = respuesta, mensaje = mensaje });
            }
        }

        #endregion

        /*--------------HERRAMIENTA---------------------*/
        #region HERRAMIENTA
        [HttpGet]
        public JsonResult listarHerramientas()
        {
            try
            {
                List<EN_Herramienta> herramientas = new List<EN_Herramienta>();
                RN_Herramienta herramienta = new RN_Herramienta();
                herramientas = herramienta.listarHerramientas();
                return Json(new { data = herramientas }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { mensaje = "Error al realizar la operacion" }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult GuardarHerramienta(EN_Herramienta objeto) /*De este json se puede controlar que mas ver, igualar elementos, etc*/
        {
            object resultado;/*Va a permitir almacenar cualquier tipo de resultado (en este caso int o booelan, dependiendi si es creacion o edicion)*/
            string mensaje = string.Empty;

            if (objeto.idValidacionHerramienta == "0")/*Es decir, si el id es 0 en inicio (el valor es 0 inicialmente) significa que es
             una Administrador nueva, por lo que se ha dado dando clic con el boton de crear*/
            {
                resultado = new RN_Herramienta().Registrar(objeto, out mensaje);/*El metodo registrar
                 de tipo int, devuelve el id registrado*/
            }
            else
            {/*Pero si el id es diferente de 0, es decir ya existe, entonces se esta editando
                 a una Administrador, por lo que indica que se ha dado clic en el boton de editar, eso lo comprobamos
                 con los alert comentados*/
                //resultado = new RN_Administrador().Editar(objeto, out mensaje);}
                //resultado = null;
                resultado = new RN_Herramienta().editarHerramienta(objeto, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult EliminarHerramienta(string id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new RN_Herramienta().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        /*--------------TIPO USUARIO---------------------*/
        #region TipoUsuario
        public JsonResult ListarTipoUsuario()
        {
            List<EN_TipoUsuario> tipoUsuarios = new List<EN_TipoUsuario>();
            RN_TipoUsuario tp_negocio = new RN_TipoUsuario();
            try
            {
                tipoUsuarios = tp_negocio.ListarTiposUsuario();
                if (tipoUsuarios != null)
                {
                    return Json(new { success = true,  data = tipoUsuarios }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, data = tipoUsuarios, message = "Se ha devuelto una lista vacía, no hay datos existentes en la base, o existe un error de código en la capa datos, depura y verifica" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        /*--------------USUARIOS---------------------*/
        #region Usuarios
        public JsonResult ListarUsuarios()
        {
            RN_Usuarios rn_usuarios = new RN_Usuarios();
            List<EN_Usuario> usuarios = new List<EN_Usuario>();
            try
            {
                usuarios = rn_usuarios.ListarUsuarios();

SistemaWeb_UnidadPracticas/Views/SIGUP/Estadisticas.cshtml
@{
    ViewBag.Title = "Estadisticas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="mt-4">Estadísticas</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Estadísticas de préstamos, herramientas, usuarios, etc</li>
</ol>

SistemaWeb_UnidadPracticas/Views/SIGUP/Index.cshtml
@{
    ViewBag.Title = "Inicio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1 class="mt-4">Principal</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Dashboard Prestamos</li>
</ol>



<div class="row">

    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6>Usuarios</h6>
                        <h6 id="totalUsuario">0</h6>
                    </div>
                    <div class="col-sm-3">
                        <i class="fas fa-user fa-2x"></i>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6>Préstamos</h6>
                        <h6 id="totalPrestamo">0</h6>
                    </div>
                    <div class="col-sm-3">
                        <i class="fas fa-landmark fa-2x"></i>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6>Herramientas</h6>
                        <h6 id="totalHerramienta">0</h6>

                    </div>
                    <div class="col-sm-3">
                        <i class="fas fa-tools fa-2x"></i>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-9">
                        <h6>Ejemplares</h6>
                        <h6 id="totalEjemplaresHerramienta">0</h6>
                    </div>
                    <div class="col-sm-3">
                        <i class="fas fa-edit fa-2x"></i>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-tags me-1"></i> @*Titulo de la tabla*@
        Historial de Préstamos
    </div>

    <div class="card-body">
        <form action="@Url.Action("ExportarPrestamo","SIGUP")" method="post">
            <div class="row align-items-end">
                <div class="col-sm-3 col-md-2">
                    <div class="mb-2">
                        <label class="form-label" for="txtFechaInicio">Fecha de Inicio:</label>
                        <input class="form-control" type="text" id="txtFechaInicio" name="fechainicio" />
                    </div>
                </div>
                <div class="col-sm-3 col-md-2">
                    <div class="mb-2">
                        <label class="form-label" for="txtFechaFin">Fecha Fin:</label>
                        <input class="form-control" type="text" id="txtFechaFin" name="fechafin" />
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="mb-2">
                        <label class="form-label" for="txtCodigo">Código Herramienta:</label>
                        <input class="form-control" type="text" id="txtCodigo" name="codigo" autocomplete="off" />
                    </div>
                </div>

                <div class="col-sm-2">
                    <div class="d-grid mb-2">
                        <button class="btn btn-primary " id="btnBuscar" type="button"><i class="fas fa-search"></i> Buscar</button>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="d-grid mb-2">
                        <button class="btn btn-success" type="submit"><i class="fas fa-file-excel"></i> Exportar</button>
                    </div>
                </div>
            </div>
        </form>
        <hr />
        <div class="row">
            <div class="col-sm-12">
                <table id="tabla" class="display cell-border" style="width:100%">
                    <thead>
                        <tr>
                            <th>Fecha del Préstamo</th>
                            <th>Usuario</th>
                            <th>Herramienta</th>
                            <th>Stock</th>
                            <th>Estado del Préstamo</th>
                            @*<th>Total</th>*@
                            <th>Código</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>.
        </div>

    </div>
</div>


@section scripts{
        <script>
            var tabladata;

            $(document).ready(function () {/* asi como entra a la pagina de dashboard se automatiza la tabla con las fechas de hoy ya que son las que estan en los input*/

                $("#txtFechaInicio").datepicker({ dateFormat: 'dd/mm/yy' }).datepicker('setDate', new Date())
                $("#txtFechaFin").datepicker({ dateFormat: 'dd/mm/yy' }).datepicker('setDate', new Date())


                /*Para mostrar totales en las tarjetas del dashboard*/
                jQuery.ajax({
                    url: '@Url.Action("VistaDashBoard", "SIGUP")',
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {/*Ese data esta almacenando la respuesta del metodo vistadashboard hecho en homeController*/
                        var objeto = data.resultado;

                        $("#totalUsuario").text(objeto.TotalUsuario),
                        $("#totalPrestamo").text(objeto.TotalPrestamo),
                        $("#totalHerramienta").text(objeto.TotalHerramienta),
                            $("#totalEjemplaresHerramienta").text(objeto.TotalEjemplaresHerramienta)

                    }
                });

                /* Para dar uso al metodo de buscar y lo muestre en una tabla resultante*/

                var Url = '@Url.Action("ListaReporte", "SIGUP")' +
                    "?fechaInicio=" + $("#txtFechaInicio").val() +
                    "&fechaFin=" + $("#txtFechaFin").val() +
                    "&codigo=" + $("#txtCodigo").val()


                tabladata = $("#tabla").DataTable({
                    responsive: true,
                    /*Para que sea resposiva*/
                    ordering: false,
                    "ajax": {
                        /*Como pinta la tabla, ajax solo trae todos los valores*/
                        url: Url,
                        type: "GET",
                        dataType: "json"
                    },
                    "columns": [
                        /*Todas las columnas que vamos a usar*/
                        
                            { "data": "FechaPrestamo", "width": "90px" },
                            { "data": "Usuario" },
                            { "data": "Herramienta" },
                            /*El nombre del segundo identificador debe ser igual al de la tabla, la columna*/
                            { "data": "Cantidad" },
                            {
                                "data": "Estado", "render": function (valor) {
                                /*El render permite obtener el valor de la columna activo*/
                                    //if (valor) {/*Si el valor es verdadero*/
                                    //    return '<span class="badge bg-success">Si</span>'
                                    //} else {
                                    //    return '<span class="badge bg-danger">No</span>'
                                    //}
                                    if (valor) {/*Si el valor es verdadero*/
                                        return '<span class="badge bg-danger">Pendiente</span>'
                                        //Si Significa que esta pendiente = 1 = Activo
                                    } else {
                                        return '<span class="badge bg-success">Devuelto</span>'
                                        //No, Significa que el prestamo devuelto = 0 = Inactivo
                                    }
                                },
                                "width": "90px"
                            },
                            { "data": "Codigo" }

                        ],
                        /*Propiedad o atributos van dentro de las comillas ""*/
                        "language": {
                            "url": "https://cdn.datatables.net/plug-ins/1.13.4/i18n/es-ES.json"
                        }

                  });
            })

           $("#btnBuscar").on("click", function (){
                var nueva_url = '@Url.Action("ListaReporte", "SIGUP")' +
                    "?fechaInicio=" + $("#txtFechaInicio").val() +
                    "&fechaFin=" + $("#txtFechaFin").val() +
                    "&codigo=" + $("#txtCodigo").val()

                //console.log(nueva_url);
                tabladata.ajax.url(nueva_url).load();
            })





        </script>
    }